quarkus:
  oidc:
    client-id: ${TODO_BACKEND_CLIENTID:xP2E7TJYaKQmh5EyFPYCmtGuIC3Drbez}
    authentication:
      scopes: openid,profile,email
    auth-server-url: ${AUTHSERVER:https://your.auth0.domain}
    credentials:
      secret: ${AUTH0SECRET}
    application-type: web_app
  http:
    port: ${TODO_BACKEND_PORT:8080}
    cors: true
    auth:
      permission:
        authenticated:
          paths: /*
          policy: authenticated

    
greeting:
  message: "hello"