quarkus:
  # oidc:
  #   client-id: ${CLIENTID:UoBBOjKU3rYy3nFu6JRCRhtLSIELnona}
  #   auth-server-url: ${AUTHSERVER:https://dev-xtuoussz.jp.auth0.com/}
  #   application-type: SERVICE
  http:
    port: ${TODO_BACKEND_PORT:8080}
    cors: true
  mongodb: 
    connection-string: ${TODO_MONGO_URL:mongodb://localhost:27017}
    database: todo

greeting:
  message: "hello"
